### ISSUE TITLE
Create a website with dashboard for the API

### ISSUE THREAD

**Issue by a3ryk** [AnimuAPI/Animu#40]
This isn't urgent however I'm up for ideas and helpers as I lack knowledge in frontend.

**Comment by MythicalMayhem** [comment]
> This isn't urgent however I'm up for ideas and helpers as I lack knowledge in frontend.

I can work on front end if there is a layout how the website should be

**Comment by a3ryk** [comment]
Please ping me on discord @Aeryk. We can talk further about this over there.

**Comment by a3ryk** [comment]
For more information, check out the [repository](https://github.com/WaifuAPI/website).
